In [1]:
from scipy import linalg as linalg

In [2]:
import numpy as np

In [10]:
F = np.array([[0,1,0,0,0,0,0,0],
[0,0,1,0,0,0,0,0],
[0,0,0,1,0,0,0,0],
[0,0,0,0,1,0,0,0],
[0,0,0,0,0,1,0,0],
[0,0,0,0,0,0,1,0],
[0,0,0,0,0,0,0,1],
[-18298808.3714549,-16446291.6380620,-6628208.73547499,-1566441.36959446,-237746.765180077,-23764.6748287380,-1530.27499166363,-58.1424972230085]])

F.shape

(8, 8)

In [11]:
B, T = linalg.matrix_balance(F)

In [12]:
B

array([[  0.        ,   2.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   4.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   8.        ,
          0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          8.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   8.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  32.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,  64.        ],
       [ -2.18138795,  -3.92110148,  -6.32115243, -11.95099922,
        -14.51091096, -11.6038451

In [15]:
np.diag(T)

array([9.53674316e-07, 1.90734863e-06, 7.62939453e-06, 6.10351562e-05,
       4.88281250e-04, 3.90625000e-03, 1.25000000e-01, 8.00000000e+00])

In [16]:
B == linalg.inv(T) @ F @ T

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [17]:
gebal = linalg.get_lapack_funcs(('gebal'), (F,))
B, lo, hi, ps, info = gebal(F, scale=True, permute=True, overwrite_a=False)

In [20]:
ps

array([9.53674316e-07, 1.90734863e-06, 7.62939453e-06, 6.10351562e-05,
       4.88281250e-04, 3.90625000e-03, 1.25000000e-01, 8.00000000e+00])

In [21]:
lo

0

In [22]:
hi

7